/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-12 23:36:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bakery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Bakery Fondant</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script><!--jquery 라이브러리-->\r\n");
      out.write("      <script src=\"../script/main.js\"></script>\r\n");
      out.write("      <script src=\"../script/jquery.cycle2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"div_main\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <nav class=\"nav_main\">\r\n");
      out.write("                <nav class=\"nav_1\">\r\n");
      out.write("                <a href=\"main.jsp\"><img src=\"../imgs/logo.png\" width=\"300px\" style=\"left: 00px;\"></a>\r\n");
      out.write("                <input type=\"submit\" value=\"로그인\" onclick=\"document.location.href='login.jsp'\">\r\n");
      out.write("                <input type=\"button\" value=\"회원가입\" onclick=\"document.location.href='agreement.jsp'\">\r\n");
      out.write("                </nav>\r\n");
      out.write("                <nav class=\"nav_2\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"menu1\"><a href=\"\">CAKE</a>\r\n");
      out.write("                            <ul class=\"sub1\">\r\n");
      out.write("                                <li><a href=\"\">생크림</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"menu1\"><a href=\"\">COOKIE</a>\r\n");
      out.write("                            <ul class=\"sub1\">\r\n");
      out.write("                                <li><a href=\"\">마들렌</a></li>\r\n");
      out.write("                                <li><a href=\"\">휘낭시에</a></li>\r\n");
      out.write("                                <li><a href=\"\">MORE</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"menu1\"><a href=\"\">CLASS</a>\r\n");
      out.write("                            <ul class=\"sub1\">\r\n");
      out.write("                                <li><a href=\"\">수업문의</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"menu1\"><a href=\"\">ORDER</a>\r\n");
      out.write("                            <ul class=\"sub1\">\r\n");
      out.write("                                <li><a href=\"\">상품주문</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"menu1\"><a href=\"\">Q&A</a>\r\n");
      out.write("                            <ul class=\"sub1\">\r\n");
      out.write("                                <li><a href=\"board.jsp\">게시판</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"cycle-slideshow\">\r\n");
      out.write("            <img src=\"../imgs/IMG_3037.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3030.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_2980.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <nav class=\"main1\">\r\n");
      out.write("                <img src=\"../imgs/IMG_2969.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3248.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3041.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3982.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_4121.jpg\">\r\n");
      out.write("            </nav>\r\n");
      out.write("            <nav class=\"main1\">\r\n");
      out.write("                <img src=\"../imgs/IMG_2793.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3760.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_3944.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_4094.jpg\">\r\n");
      out.write("                <img src=\"../imgs/IMG_4150.jpg\">\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer class=\"ft1\">\r\n");
      out.write("            <nav class=\"nv3\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">HOME</a></li>\r\n");
      out.write("                    <li><a href=\"|1\">|</a></li>\r\n");
      out.write("                    <li><a href=\"\">TERMS</a></li>\r\n");
      out.write("                    <li><a href=\"|1\">|</a></li>\r\n");
      out.write("                    <li><a href=\"\">BAKERY</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <nav class=\"nv4\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>OWNER: Sweet Devils Baking</li>\r\n");
      out.write("                    <li>E-mail:happyhome@sweet.kr</li>\r\n");
      out.write("                    <li>TELL:032-345-6789</li>\r\n");
      out.write("                    <li>ADDRESS:인천광역시 00구 00동</li>\r\n");
      out.write("                    <li>BUSINESS LICENSE:2719619328</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
